### ISSUE TITLE
Course of Study: Third-party database interface for TPS school course catalogs

### ISSUE THREAD

**Issue by TroyRobinson** [tulsaschoolsdata/courses#1]
~ courses.tulsaschools.org

For traffic coming from: https://github.com/tulsaschoolsdata/courses/issues/2

**Mockup**: https://www.figma.com/file/ZUTuZLnC305DO8dURRWt6j/Find-a-School-Course-of-Study?node-id=2%3A2
**Project Plan**: https://app.smartsheet.com/sheets/Q9j7rR4j62Vfgj9MpQ39C2rgw8qmwfF86Mw5JHC1

<img width="864" alt="image" src="https://user-images.githubusercontent.com/24643126/174405413-98a8dfda-9675-47b7-96f3-1fb29f1b97de.png">
- screenshot is up-to-date as of 06/17/2022

### Requirements

- [x] Lists courses as cards with type-tags and descriptions.
- [x] Course cards list is filterable by school (see requirements of tulsaschoolsdata/courses#2), course type, grade-level, and potentially other criteria (pending stakeholder feedback)

⚠ Not sure if grade levels should be a filter, given that the grade itself doesn't always determine which classes a student can take.

**Comment by mcclatr** [comment]
https://docs.google.com/document/d/1BswLvxIhva3LWQjaCy5-fm9Qao5D2Ud5mTcCqOgVU6E/edit

https://docs.google.com/document/d/1Q18VYt29_Ai1v_G39lrwpGQN98tlYk-o0JG6peaRym8/edit#heading=h.svq68hhhcnoq

**Comment by nestor-custodio** [comment]
# Post-Demo Discussion

## Data

- DONE: we now have a credit type code-to-name mapping codeset that kriss will be maintaining
- TODO: request additional data around credit types so we can surface planning-related info?
- TODO: pull "vocational = true/yes" + "instructional level" flags so we can add filters for "tulsa tech" and thelike
- TODO: build process can be made to tweak catalog data for easier slurping on initial load
- TODO: add a "school_categories" array on course records


## Presentation

- TODO: description truncation should happen via a css "overflow" rule, not by truncating the text we're feeding into the page
- TODO: sort course list by name
- TODO: switch course listing from Material cards to a DataTable
- TODO: add school category badging to courses


## Open For Discussion

- yank courses with a non-numeric course_number; IMO this should happen on the the data pull query and is done already, but am open to discussion
- yank "attendance" / "homeroom" / "self" / "monitoring" -related "courses"; same as above
